/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1_199819880;

import javax.swing.JScrollPane;

/**
 *
 * @author Allan
 */
public class CatalogoZombies extends javax.swing.JFrame {

    /**
     * Creates new form CatalogoZombies
     */
    public CatalogoZombies(ListaCatalogoZombies lista) {
        initComponents();
        labelszombies panel = new labelszombies(lista);
       
       JScrollPane scrollPane = new JScrollPane(panel);
       scrollPane.setBounds(10, 43, 700, 300);
       scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
       scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
       
       this.add(scrollPane);
   
       this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnagregarplanta = new javax.swing.JButton();
        btninsertarzombies = new javax.swing.JButton();
        btncerrar = new javax.swing.JButton();
        lbltitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnagregarplanta.setFont(new java.awt.Font("HouseofTerror", 0, 18)); // NOI18N
        btnagregarplanta.setText("Agregar Plantas");

        btninsertarzombies.setFont(new java.awt.Font("HouseofTerror", 0, 18)); // NOI18N
        btninsertarzombies.setText("Agregar Zombies");
        btninsertarzombies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsertarzombiesActionPerformed(evt);
            }
        });

        btncerrar.setFont(new java.awt.Font("HouseofTerror", 0, 18)); // NOI18N
        btncerrar.setText("Cerrar");
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });

        lbltitulo.setFont(new java.awt.Font("HouseofTerror", 0, 18)); // NOI18N
        lbltitulo.setText("CATALOGO ZOMBIES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(lbltitulo))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btncerrar)
                .addGap(250, 250, 250)
                .addComponent(btninsertarzombies)
                .addGap(31, 31, 31)
                .addComponent(btnagregarplanta))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbltitulo)
                .addGap(373, 373, 373)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(btncerrar))
                    .addComponent(btninsertarzombies)
                    .addComponent(btnagregarplanta)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btninsertarzombiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsertarzombiesActionPerformed
        // TODO add your handling code here:
        InsertarZombies insertar = new InsertarZombies();
        insertar.setVisible(true);
        insertar.setResizable(false);
        insertar.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btninsertarzombiesActionPerformed

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_btncerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CatalogoZombies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CatalogoZombies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CatalogoZombies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CatalogoZombies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new CatalogoZombies().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregarplanta;
    private javax.swing.JButton btncerrar;
    private javax.swing.JButton btninsertarzombies;
    private javax.swing.JLabel lbltitulo;
    // End of variables declaration//GEN-END:variables
}
