/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1_199819880;

import java.awt.Color;
import java.awt.GridLayout;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.LineBorder;

/**
 *
 * @author Allan
 */
public class Juego extends javax.swing.JFrame {

    //int n= 2, m=4;
    
    //Etiqueta[][] label = new Etiqueta[n][m];
    /**
     * Creates new form Juego
     */
    public Juego() {
        initComponents();
        
        //PanelJuego.setLayout(new GridLayout(n,m));
        
        //setTitle("Plants vs Zombies Guatemalteco");
        //setLayout(null);
        //for (int i = 0; i<n;i++){
       // final int ii=i;
        //for(int j=0;j<m;j++){
          //  final int jj=j;
            
         //   label[ii][jj] = new Etiqueta();
          //  label[ii][jj].setBackground(Color.GREEN);
            //label[ii][jj].setBorder(LineBorder.createGrayLineBorder());
          //  label[ii][jj].setBounds(15+ii*10, 30+jj*10, 10, 10);
           // label[ii][jj].setVisible(true);
           // this.add(label[ii][jj]);
           // PanelJuego.add(label[ii][jj]);
            
        
        
        //}
        
        //}
        
        Pilazombies pila = new Pilazombies();
        ApiladorZombies apilador = new ApiladorZombies(pila);
        
        ExecutorService ejecutor = Executors.newCachedThreadPool();
        ejecutor.execute(apilador);
        
          ColaPlantas cola = new ColaPlantas();
        Encoladorplantas encolador = new Encoladorplantas(cola);
        
        
        ejecutor.execute(encolador);
        
     
        
    }
public void matriz(int n,int m)
    {
       
        Etiqueta[][] label = new Etiqueta[n][m];
        PanelJuego.setLayout(new GridLayout(n,m));
       
        setTitle("Plants vs Zombies Guatemalteco");
        setLayout(null);
        for (int i = 0; i<n;i++){
        final int ii=i;
        for(int j=0;j<m;j++){
            final int jj=j;
            
            label[ii][jj] = new Etiqueta();
            label[ii][jj].setBackground(Color.GREEN);
            //label[ii][jj].setBorder(LineBorder.createGrayLineBorder());
            label[ii][jj].setBounds(15+ii*10, 30+jj*10, 10, 10);
            label[ii][jj].setVisible(true);
            this.add(label[ii][jj]);
            PanelJuego.add(label[ii][jj]);
            
        
        
        }
        
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelJuego = new javax.swing.JPanel();
        panelzombiescola = new javax.swing.JScrollPane();
        panelPlantaspila = new javax.swing.JScrollPane();
        btnlistaplantagrafica = new javax.swing.JButton();
        btncatalgoplantasgrafica = new javax.swing.JButton();
        btnlistazombiegrafica2 = new javax.swing.JButton();
        btncatalgozombiesgrafica1 = new javax.swing.JButton();
        btncolaplantasgrafica = new javax.swing.JButton();
        btnPilaZombiesgrafica1 = new javax.swing.JButton();
        btncolaplantasgrafica1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelJuego.setPreferredSize(new java.awt.Dimension(500, 380));

        javax.swing.GroupLayout PanelJuegoLayout = new javax.swing.GroupLayout(PanelJuego);
        PanelJuego.setLayout(PanelJuegoLayout);
        PanelJuegoLayout.setHorizontalGroup(
            PanelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        PanelJuegoLayout.setVerticalGroup(
            PanelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        getContentPane().add(PanelJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 550, 390));
        getContentPane().add(panelzombiescola, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, 100, 380));
        getContentPane().add(panelPlantaspila, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 100, 380));

        btnlistaplantagrafica.setFont(new java.awt.Font("HouseofTerror", 0, 18)); // NOI18N
        btnlistaplantagrafica.setText("Reporte lista Jugador Plantas");
        btnlistaplantagrafica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistaplantagraficaActionPerformed(evt);
            }
        });
        getContentPane().add(btnlistaplantagrafica, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        btncatalgoplantasgrafica.setFont(new java.awt.Font("HouseofTerror", 0, 18)); // NOI18N
        btncatalgoplantasgrafica.setText("Reporte Catalogo Plantas");
        btncatalgoplantasgrafica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncatalgoplantasgraficaActionPerformed(evt);
            }
        });
        getContentPane().add(btncatalgoplantasgrafica, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, -1, -1));

        btnlistazombiegrafica2.setFont(new java.awt.Font("HouseofTerror", 0, 18)); // NOI18N
        btnlistazombiegrafica2.setText("Reporte lista Jugador Zombie");
        btnlistazombiegrafica2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlistazombiegrafica2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnlistazombiegrafica2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, -1, -1));

        btncatalgozombiesgrafica1.setFont(new java.awt.Font("HouseofTerror", 0, 18)); // NOI18N
        btncatalgozombiesgrafica1.setText("Reporte Catalogo Zombies");
        btncatalgozombiesgrafica1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncatalgozombiesgrafica1ActionPerformed(evt);
            }
        });
        getContentPane().add(btncatalgozombiesgrafica1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, -1, -1));

        btncolaplantasgrafica.setFont(new java.awt.Font("HouseofTerror", 0, 18)); // NOI18N
        btncolaplantasgrafica.setText("Reporte Cola Plantas");
        getContentPane().add(btncolaplantasgrafica, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 500, -1, -1));

        btnPilaZombiesgrafica1.setFont(new java.awt.Font("HouseofTerror", 0, 18)); // NOI18N
        btnPilaZombiesgrafica1.setText("Reporte Pila Zombies");
        getContentPane().add(btnPilaZombiesgrafica1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 460, -1, -1));

        btncolaplantasgrafica1.setFont(new java.awt.Font("HouseofTerror", 0, 18)); // NOI18N
        btncolaplantasgrafica1.setText("Cerrar");
        btncolaplantasgrafica1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncolaplantasgrafica1ActionPerformed(evt);
            }
        });
        getContentPane().add(btncolaplantasgrafica1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica1_199819880/matriz.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlistaplantagraficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistaplantagraficaActionPerformed
        // TODO add your handling code here:
        
        ListaJugador.Plantas.Dibujar();
            ListaJugador.Plantas.GenerarPNG();
            Runtime runtime = Runtime.getRuntime();
        try {
            runtime.exec("mspaint ListaJugadorPlantas.png");
            
        } catch (Exception ex) {
            Logger.getLogger(CatalogoPlantas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnlistaplantagraficaActionPerformed

    private void btnlistazombiegrafica2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlistazombiegrafica2ActionPerformed
        // TODO add your handling code here:
        
        ListaJugadorZombie.Zombie.Dibujar();
           ListaJugadorZombie.Zombie.GenerarPNG();
            Runtime runtime = Runtime.getRuntime();
        try {
            runtime.exec("mspaint ListaJugadorZombies.png");
            
        } catch (Exception ex) {
            Logger.getLogger(CatalogoPlantas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnlistazombiegrafica2ActionPerformed

    private void btncatalgoplantasgraficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncatalgoplantasgraficaActionPerformed
        // TODO add your handling code here:
        ListaCatalogoPlantas.listacatalogo.Dibujar();
           ListaCatalogoPlantas.listacatalogo.GenerarPNG();
            Runtime runtime = Runtime.getRuntime();
        try {
            runtime.exec("mspaint ListaCatalogoPlantas.png");
            
        } catch (Exception ex) {
            Logger.getLogger(CatalogoPlantas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btncatalgoplantasgraficaActionPerformed

    private void btncolaplantasgrafica1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncolaplantasgrafica1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btncolaplantasgrafica1ActionPerformed

    private void btncatalgozombiesgrafica1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncatalgozombiesgrafica1ActionPerformed
        // TODO add your handling code here:
         ListaCatalogoZombies.listacatalogo.Dibujar();
           ListaCatalogoZombies.listacatalogo.GenerarPNG();
            Runtime runtime = Runtime.getRuntime();
        try {
            runtime.exec("mspaint ListaCatalogoZombies.png");
            
        } catch (Exception ex) {
            Logger.getLogger(CatalogoPlantas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btncatalgozombiesgrafica1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelJuego;
    private javax.swing.JButton btnPilaZombiesgrafica1;
    private javax.swing.JButton btncatalgoplantasgrafica;
    private javax.swing.JButton btncatalgozombiesgrafica1;
    private javax.swing.JButton btncolaplantasgrafica;
    private javax.swing.JButton btncolaplantasgrafica1;
    private javax.swing.JButton btnlistaplantagrafica;
    private javax.swing.JButton btnlistazombiegrafica2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane panelPlantaspila;
    private javax.swing.JScrollPane panelzombiescola;
    // End of variables declaration//GEN-END:variables
}
